

const Affirmations = [

    "I am worthy of love and happiness.",
    "I believe in my abilities.",
    "I attract positivity into my life.",
    "I am grateful for all that I have.",
    "I am in control of my thoughts and emotions.",
    "I am resilient and can overcome any challenges.",
    "I trust the journey of my life.",
    "I am constantly evolving and growing.",
    "I am at peace with my past.",
    "I am open to new opportunities.",
    "I am confident in my decisions.",
    "I radiate self-confidence and inner strength.",
    "I am surrounded by love and support.",
    "I am kind and compassionate towards others.",
    "I embrace change as a chance for growth.",
    "I am a source of positivity for those around me.",
    "I am in harmony with the universe.",
    "I am deserving of success and happiness.",
    "I am a magnet for abundance.",
    "I am in tune with my inner wisdom.",
    "I am free to be myself.",
    "I am releasing all negativity from my life.",
    "I am living a life filled with joy and purpose.",
    "I am open to receiving love and blessings.",
    "I am the architect of my own destiny.",
    "I am the creator of my reality.",
    "I am grateful for the present moment.",
    "I am a source of inspiration to others.",
    "I am always moving towards my goals.",
    "I am loved and cherished by those around me.",
    "I am a unique and valuable individual.",
    "I am making a positive impact on the world.",
    "I am aligned with my true self.",
    "I am attracting success and abundance.",
    "I am letting go of fear and doubt.",
    "I am in perfect health and vitality.",
    "I am open to new possibilities.",
    "I am a beacon of light and positivity.",
    "I am surrounded by beauty and abundance.",
    "I am a confident and capable person.",
    "I am a loving and compassionate soul.",
    "I am forgiving and understanding.",
    "I am open to receiving all the good in life.",
    "I am at peace with my past and excited for my future.",
    "I am grateful for the lessons I've learned.",
    "I am connected to the wisdom of the universe.",
    "I am attracting positive and loving relationships.",
    "I am grateful for the gift of life.",
    "I am a magnet for success and prosperity.",
    "I am in control of my thoughts and emotions.",
    "I am capable of achieving my dreams.",
    "I am a source of strength for others.",
    "I am open to the abundance of the universe.",
    "I am creating a life I love.",
    "I am at peace with the past and hopeful for the future.",
    "I am open to new experiences and adventures.",
    "I am in harmony with the world around me.",
    "I am worthy of all the good that comes my way.",
    "I am resilient and capable of handling challenges.",
    "I am confident and believe in myself.",
    "I am attracting positive and loving people.",
    "I am open to love and compassion.",
    "I am a vessel of positive energy.",
    "I am in tune with my inner wisdom.",
    "I am free to be myself and express my true feelings.",
    "I am releasing all negativity from my life.",
    "I am embracing change and growth.",
    "I am a magnet for abundance and success.",
    "I am always learning and growing.",
    "I am a beacon of light and positivity for others.",
    "I am deserving of love and happiness.",
    "I am at peace with my past and excited for my future.",
    "I am open to new opportunities and possibilities.",
    "I am in control of my thoughts and emotions.",
    "I am resilient and strong.",
    "I am a source of inspiration to others.",
    "I am open to receiving all the good in life.",
    "I am connected to the wisdom of the universe.",
    "I am attracting positive and loving relationships.",
    "I am grateful for the gift of life.",
    "I am a magnet for success and prosperity.",
    "I am in control of my destiny.",
    "I am confident and capable.",
    "I am loving and compassionate.",
    "I am open to love and compassion.",
    "I am a vessel of positive energy and love.",
    "I am in tune with my inner guidance.",
    "I am free to express my true self.",
    "I am releasing all negativity and fear.",
    "I am embracing change and growth.",
    "I am a magnet for abundance and joy.",
    "I am always evolving and improving.",
    "I am a beacon of light and positivity.",
    "I am deserving of love and happiness.",
    "I am at peace with my past and excited for my future.",
    "I am open to new possibilities and adventures.",
    "I am in harmony with the universe.",
    "I am in control of my destiny and success.",
    "I am a source of inspiration and positivity.",
    "I am grateful for the abundance and blessings in my life."
];


export default Affirmations;



